import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TranslationProvider from "./translation/TranslationProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Enoves",
  description: "Generated by create next app",
};

import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import TranslationPrompt from "./components/translation/TranslationPrompt";

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body
        className={ `${geistSans.variable} ${geistMono.variable} antialiased` }
      >
        <TranslationProvider>
          <TranslationPrompt />
          <Header />
          { children }
          <Footer />
        </TranslationProvider>
      </body>
    </html>
  );
}
